# version özelliği kaldırıldı (obsolete)

services:
  web:
    image: nginx:latest 
    platform: linux/amd64  # Platform belirtme
    ports:
      - "8080:80"
    volumes:
      - ./html:/usr/share/nginx/html
    networks:
      - webnet

  db:
    image: mysql:5.7
    platform: linux/amd64  # Platform belirtme
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: sampledb
      MYSQL_USER: sampleuser
      MYSQL_PASSWORD: samplepassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - webnet

networks:
  webnet:

volumes:
  db_data: